apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yntrust-dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: 172.16.10.17:7747/yntrust-dev/code-sandbox
    newName: 172.16.10.17:7747/yntrust-dev/code-sandbox
    newTag: latest
patches:
  - path: service-patch.yaml
